# Estados
ESTADO_ACTIVO = 1
ESTADO_INACTIVO = 2

# Tipos de movimiento
MOVIMIENTO_INGRESO = 1
MOVIMIENTO_EGRESO = 2

# Estados de préstamo
PRESTAMO_SOLICITADO = 1
PRESTAMO_APROBADO = 2
PRESTAMO_DESEMBOLSADO = 3
PRESTAMO_EN_MORA = 4

# Roles
ROL_PRESIDENTE = 1
ROL_SECRETARIO = 2
ROL_TESORERO = 3
ROL_MIEMBRO = 5
